# Generated by Django 5.2.4 on 2025-08-20 13:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlurPelayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.BigIntegerField()),
                ('namobj', models.CharField(max_length=250)),
                ('orde01', models.BigIntegerField()),
                ('orde02', models.BigIntegerField()),
                ('orde03', models.BigIntegerField()),
                ('orde04', models.BigIntegerField()),
                ('jnsrsr', models.BigIntegerField()),
                ('stsjrn', models.BigIntegerField()),
                ('wadmpr', models.CharField(max_length=250)),
                ('remark', models.CharField(max_length=250)),
                ('sbdata', models.CharField(max_length=250)),
                ('keterangan', models.CharField(blank=True, max_length=250, null=True)),
                ('km', models.FloatField()),
                ('shape_leng', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
    ]
