# Generated by Django 5.2.4 on 2025-09-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadZipFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipfile', models.FileField(upload_to='data/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='alurpelayaran',
            options={'ordering': ['objectid'], 'verbose_name': 'Alur Pelayaran', 'verbose_name_plural': 'Alur Pelayaran'},
        ),
    ]
