# Generated by Django 5.2.4 on 2025-10-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_base', '0004_kabelbawahlaut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kabelbawahlaut',
            old_name='geom',
            new_name='shapes',
        ),
    ]
