# Generated by Django 5.2.4 on 2025-10-01 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_base', '0005_rename_geom_kabelbawahlaut_shapes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KabelBawahLaut',
        ),
    ]
