# Generated by Django 5.2.4 on 2025-10-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_base', '0011_kabelbawahlaut'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KabelBawahLaut',
        ),
    ]
