# Generated by Django 5.2.4 on 2025-10-01 07:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_base', '0012_delete_kabelbawahlaut'),
    ]

    operations = [
        migrations.CreateModel(
            name='KabelBawahLaut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.BigIntegerField(blank=True, null=True)),
                ('namobj', models.CharField(blank=True, max_length=250, null=True)),
                ('orde01', models.BigIntegerField(blank=True, null=True)),
                ('orde02', models.BigIntegerField(blank=True, null=True)),
                ('orde03', models.BigIntegerField(blank=True, null=True)),
                ('orde04', models.BigIntegerField(blank=True, null=True)),
                ('jnsrsr', models.BigIntegerField(blank=True, null=True)),
                ('stsjrn', models.BigIntegerField(blank=True, null=True)),
                ('wadmpr', models.CharField(blank=True, max_length=250, null=True)),
                ('remark', models.CharField(blank=True, max_length=250, null=True)),
                ('sbdata', models.CharField(blank=True, max_length=250, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=90, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'verbose_name': 'Kabel Bawah Laut',
                'verbose_name_plural': 'Kabel Bawah Laut',
                'ordering': ['objectid'],
            },
        ),
    ]
