# Generated by Django 5.2.4 on 2025-10-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_base', '0014_migas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KabelBawahLaut',
        ),
        migrations.DeleteModel(
            name='Migas',
        ),
    ]
